import os

# Беремо токен з Railway, а якщо його немає - підставляємо напряму
TELEGRAM_API_KEY = os.getenv("TELEGRAM_API_KEY", "7795357191:AAFyesKdhD0VLpsC9-RAZRj0VS5DS7Tip-k")
TELEGRAM_APKEY = TELEGRAM_API_KEY

# Ключі Binance
BINANCE_API_KEY = "3v2KzK8lhtYblymiQiRd9aFxuRZXOuv3wdgZnVgPGTWSIw7WQUYxxrPlf9cYQ8ul"
BINANCE_SECRET_KEY = "aFXnMhVhhet45dBQyxVbJzVgJS5pSUsC8P7SvDvGS1Tn0WDkWMKQMD3PdZUOOitR"

TELEGRAM_APKEY = "AAFyesKdhD0VLpsC9-RAZRj0VS5DS7Tip-k"
API_KEY = "3v2KzK8lhtYblymiQiRd9aFxuRZXOuv3wdgZnVgPGTWSIw7WQUYxxrPlf9cYQ8ul"
SECRET_KEY = "aFXnMhVhhet45dBQyxVbJzVgJS5pSUsC8P7SvDvGS1Tn0WDkWMKQMD3PdZUOOitR"
